- app/src/main/res/values-de/strings.xml
In line 52 "Simple SMS Messenger - Nachrichten einfach verwalten" would be nicer, but has more than 50 characters.
So I edited it to "simple" which is also correct and delete 2 spaces. Not the best for styling though...
> Translated german strings

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ThreadAdapter.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt
Hi,
I've fixed the issue that last message on conversation list wasn't updating after deleting the last message in a thread. I did it by removing the entry in Android's Thread table and then fetching data from it once again (it invokes recreating the data in it once again). It has to be done like this, because deleting the message doesn't trigger automatic update of this table, and it's impossible to update it manually.
**Before:**
**After:**
> Fixed updating last message after deleting (#167)

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ConversationsAdapter.kt
- app/src/main/res/menu/cab_conversations.xml
As requested in #161, now the user has the possibility to mark as "Read" also those conversations he has not read yet.
This action can be done on multiple conversations.
> Conversations can be marked as "Read" from the main message cab

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ConversationsAdapter.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt
- app/src/main/res/layout/item_conversation.xml
Hi,
I've added support for saving unfinished SMS messages as drafts and handling them correctly in the app:
- Drafts are saved in phone's memory (Telephony.Sms.Draft table).
- In the main activity, I'm showing either a draft (if exists) or last message.
- If draft is displayed in the main activity, I've added an indicator text next to it.
- In thread activity, if there's a draft, it's automatically filling the text editor (onResume).
- If there's anything in text editor, it's saved as a draft in activity's onPause.
- If text editor in a thread has been left empty, draft is removed (also in onPause).
- To keep conversations list updated, I'm invoking update event in thread activity's onPause.
What is missing is saving MMS to the drafts. I've tried to do it, but unfortunately it didn't work …
> Added SMS drafts support (#83)

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/NewConversationActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
Hi,
I've fixed the issue with missing plus sign after tapping send message in a third-party app. Also, in the same issue there was a related issue, that it wasn't possible to enter number with plus sign manually, that is also fixed by this PR.
Implementation details:
- Fix for plus sign was very easy - string from intent was decoded by URLDecoder that replaces `+` with a space. The solution was to replace the plus sign with its URL Encoded counterpart (`%2b`)
- The problem started later. Android caches the thread IDs after generating them, even if there was no message send. Due to this, even when I did this fix, it still wasn't working. Also, due to this, issue author couldn't write a number with plus manually - he was just writing the same number, and Android was reverting thread with …
> Fixed missing plus sign when opened from another app (#107)

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ConversationsAdapter.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/MarkAsReadReceiver.kt
Hi,
I've found a bug that "mark as read" in notification and "mark as unread" in the conversation list weren't refreshing the conversation list, therefore it looks like they weren't working. I've fixed it, and additionally I've added unselecting conversations after tapping "mark as unread" (mark as read already had it). Also, I've fixed a small compiler error in ThreadActivity.
**Before:**
https://user-images.githubusercontent.com/85929121/133305042-2bf6dc78-baca-4636-a1ef-8467a462fa5b.mp4
**After:**
https://user-images.githubusercontent.com/85929121/133304913-961e966a-d762-46aa-a84b-c78a0aca6d48.mp4
> Fixed marking as read/unread not refreshing list

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ConversationsAdapter.kt
Hi,
Buttons to mark as read/unread were always visible despite the state of conversation. I've added simple conditions to make them appear only when it makes sense.
**Before:**
https://user-images.githubusercontent.com/85929121/133972456-0ea528fd-2fa0-41c5-9587-ad3e31a62d7a.mp4
**After:**
https://user-images.githubusercontent.com/85929121/133972473-f052327b-9aa9-4954-b4ee-0a2636641de1.mp4
> Added hiding option "mark as read/unread" for conversations

- app/build.gradle
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ThreadAdapter.kt
- app/src/main/res/menu/cab_thread.xml
**Notes**
- handle long-press of a message bubble
- update commons dependency
- fix broken drawable resource reference in `cab_thread` menu file
- should address this [issue](https://github.com/SimpleMobileTools/Simple-SMS-Messenger/issues/139)
- [this PR](https://github.com/SimpleMobileTools/Simple-Commons/pull/1193) in the commons library needs to be merged before it can be built 
**Screenshot**
https://user-images.githubusercontent.com/25648077/141169306-0aa228d8-a55e-4ace-8c2a-6c7ef60a86e4.mov
> handle long-press of message bubble

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ThreadAdapter.kt
- app/src/main/res/menu/cab_thread.xml
Hi,
I've added an ability to save MMS attachment. It looks like this:
- Currently it's saving only one attachment, saving multiple would be hard to achieve without permissions to write to storage.
- It should work with any kind of attachment. I've tested it only with images and videos, but since I'm just copying the original mime type from the attachment, it should also work with contact cards or other attachments.
- As a file name, I'm taking the MMS ID from the database.
- I've hidden buttons for copy, share and select text for MMS when they don't have text, since they work only for text.
https://user-images.githubusercontent.com/85929121/142726647-1a75a863-53f7-4d69-b726-2473e6f378d7.mp4
> Added saving MMS (#106)

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
Hi,
I've found a bug, that it wasn't possible to add a private contact to the group if the existing thread was with a public contact. To fix it, I had to move the private contacts fetching above the first return, because the list was always empty for public contact threads.
**Before:**
https://user-images.githubusercontent.com/85929121/150825917-bc22fa05-c202-44ae-8447-0fc50b7e92d3.mp4
**After:**
https://user-images.githubusercontent.com/85929121/150825937-6930d248-e725-4d9c-b3e7-1be3045733df.mp4
> Fixed private contacts not showing in group autocomplete

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/DirectReplyReceiver.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/services/HeadlessSmsSendService.kt
- in `Context.getMessages`, split the sender number by spaces " " to get each contact.
- apply update in the `android-smsmms` library - do not pass `threadId` in `Transaction.sendNewMessage`
- the `android-smsmms` library should be update after merging [this PR ](https://github.com/tibbi/android-smsmms/pull/1)
https://user-images.githubusercontent.com/25648077/166129734-8283e7e4-5c08-4845-a886-eabacd462d78.mp4
> handle sending group SMS

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/helpers/Config.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/models/ThreadDateTime.kt
Task description:
If you open a conversation with many messages and scroll up quickly after opening, once the messages get refetched, the scroll position returns to the bottom. We should keep the scroll position, especially if no new messages are found.
> Fix scroll position resetting on refresh

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ThreadAdapter.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/DirectReplyReceiver.kt
Closes https://github.com/SimpleMobileTools/Simple-SMS-Messenger/issues/378
Order of preference:
1. SIM selected manually by the user is always preferred.
2. SIM corresponding to the last received message's address.
3. SIM selected as the default for SMS in android settings.
EDIT: Reorder preference as per the [latest commit](https://github.com/SimpleMobileTools/Simple-SMS-Messenger/pull/431/commits/52e18200b8810225630bff388c4f47717769e52f)
> Respect default SMS SIM setting

- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ConversationDetailsActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/MainActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ConversationsAdapter.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ThreadAdapter.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/databases/MessagesDatabase.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/dialogs/RenameConversationDialog.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Activity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/models/Conversation.kt
- app/src/main/res/layout/activity_conversation_details.xml
- app/src/main/res/layout/dialog_rename_conversation.xml
- app/src/main/res/menu/cab_conversations.xml
- app/src/main/res/menu/menu_thread.xml
Closes https://github.com/SimpleMobileTools/Simple-SMS-Messenger/issues/472
- Added ability to rename groups, name changes are lost on uninstall or when app storage is cleared. 
- Added conversation details page.
> Add ability to change group names

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ConversationsAdapter.kt
The pin drawable wasn't shown on the conversation until the next refresh, this PR fixes that.
> Update conversation items on pin/unpin

- app/build.gradle
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/MainActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ConversationsAdapter.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ThreadAdapter.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/helpers/NotificationHelper.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/DirectReplyReceiver.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/SmsReceiver.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/SmsStatusSentReceiver.kt
Closes https://github.com/SimpleMobileTools/Simple-SMS-Messenger/issues/505
This PR also fixes an issue related to "Mark as read" on some devices. There's still a minor issue on android 13 devices that is also experienced by other apps and we cannot fix it without using [hacks](https://github.com/SimpleMobileTools/Simple-SMS-Messenger/issues/505#issuecomment-1341081117).
- Move notification-related code to a separate helper
- Update notification instead of canceling it when sending inline replies
- Disable notification sound on inline replies
- Reuse existing Transaction API extensions for sending inline replies
> Improve and organise notification related code

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt
Fixes #537
Seems that function for running DB queries from Commons wasn't properly working in this case. I've written it from the basis here (fetching draft for one conversation was already done without it) and it looks to work fine. I haven't changed it in Commons because I don't know all usages of the function and could break something after changing the loop's body.
**Before:**
**After:**
> Fixed showing all drafts (#537)

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
Previously the indicator kept loading forever. Also cleaned up placeholder show/hide logic.
> Hide progress bar after loading conversations from telephony

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ConversationDetailsActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/MainActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/MmsReceiver.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/SmsReceiver.kt
Closes https://github.com/SimpleMobileTools/Simple-SMS-Messenger/issues/574
- Added an extension `insertOrUpdateConversation()` to easily update a conversation while handling renamed conversations. It's only needed when updating the local db from telephony.
- On the conversation details screen, fetch participants lists from `messages` database in case the conversation has no real messages. 
- Keep renamed conversation name in scheduled conversations.
> Avoid resetting conversation name when new messages are received

- app/src/main/AndroidManifest.xml
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
Link to bug report: https://github.com/SimpleMobileTools/Simple-SMS-Messenger/issues/457
The issue was that every time the notification for a message was clicked, a new ThreadActivity was added to the stack. Not only did this require users to hit back through multiple conversations to reach the MainActivity, but after a while would cause the application to lag due to too many activities being open. I've remedied this by assigning the launch mode of singleTop to the ThreadActivity. Now if ThreadActivity is the top of the stack and a notification is tapped, the current activity will be recreated with the new conversation from the notification.
> Made ThreadActivity launch in singleTop mode and added onNewIntent.

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/helpers/MessagesImporter.kt
The previous implementation assumed that each JSON object would have an "SMS" key and a "MMS" key, and in that order. This caused an exception when it tried to read the next NAME token because the next token is actually the closing bracket of the object. This commit fixes this issue by checking that the next token is actually a NAME. If it is, we consume the token and handle it according to its value, which may be either "sms" or "mms". If it's neither of those, we skip it.
Fixes #646
> Fix import for partial exports

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt
all mms are always loaded, the number of messages only concerns sms, so only reference sms to determine the oldest loaded message
this should load all sms messages when there are mms messages in between.
until now if a mms message was the first message only messages before it would be loaded and not the messages > `MESSAGE_LIMIT` but after the mms.
Fixes: #535
> refresh sms history based on oldest sms loaded, ignoring mms

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ThreadAdapter.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/databases/MessagesDatabase.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/models/Message.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/MmsReceiver.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/SmsReceiver.kt
Application was always picking first participant when tapping on avatars in conversations. It was also using first participant for MMS notifications.
This stores sender's phone number in the database, so it can be used to look up correct participant in the list of participants. If matching on number fails, matching on name is attempted. If both of these fail, it falls back to previous behavior, which is just picking the first participant.
This may also be connected to #32, but I am not sure, since this should just be related to behavior when tapping on avatars. Mixing up avatars in the conversation should be a different issue.
This closes #433, closes #500, closes #384
> Properly look up participants in MMS group conversations

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/DirectReplyReceiver.kt
[ISSUE-675](https://github.com/SimpleMobileTools/Simple-SMS-Messenger/issues/675) The application was not updating the last conversation when you reply a message from the notification actions. We had to launch the app and refresh to see the cache refreshing. This PR updates the last message in the conversation after you reply. Now when you launch the app and you are able to see the expected state.
> [ISSUE-675] update last conversation message after replying from notification.

- app/build.gradle
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/App.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/MmsReceiver.kt
This implements the getMmscInfoForReceptionAck method in MmsReceiver which is according to android-smsmms library required for some carriers, since otherwise MMS would be duplicated. Unfortunately,
accessing MMSC information is more restricted with each version of Android and this implementation relies on system database on older versions and uses APN database included with android-smsmms for newer versions, which will work only on the default SIM card.
> Ensure that MMS reception ACK is sent to prevent duplicate MMS

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/App.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/MmsReceiver.kt
Using ApnUtils causes crash on newer Android versions (https://github.com/SimpleMobileTools/Simple-SMS-Messenger/pull/683#issuecomment-1637036718) This reverts this part of changes from https://github.com/SimpleMobileTools/Simple-SMS-Messenger/pull/687, since other changes have fixed the issue. This part is not as important (required to send reception ACK to MMSC, which is apparently not needed for all carriers)
> Remove ApnUtils usage in the app

- app/build.gradle
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/MainActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
Add Asking for Exact alarm permission before Scheduling a message to avoid Issues caused by the exact alarm scheduling on Android 14. I also updated the Commons library version to use the new string for Alarm Permission Requests. 
This PR can be simplified by using the updates that I pushed on this PR for the Commons Library: https://github.com/SimpleMobileTools/Simple-Commons/pull/1743. If the Commons Library's PR is approved, I can update this PR to use the new Commons function and extension.
> add asking for Exact alarm permission before scheduling 

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/messaging/Messaging.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/messaging/MessagingUtils.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/MmsSentReceiver.kt
This prevents duplication by ensuring that message is just updated in case of SMS, instead of creating a new entry. In case of MMS, due to the way it is sent internally, we delete original message once we get result of the new one.
This closes #554
> Prevent duplication of messages on resend

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/AutoCompleteTextViewAdapter.kt
`performFiltering` is always called on a worker thread. UI should only be updated in `publishResults`.
> Avoid modifying items while list is being updated

- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/MainActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ConversationsAdapter.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/helpers/Config.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/helpers/Constants.kt
- app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/SmsReceiver.kt
> Prevent using `archive` table if it doesn't exist
