SimpleMobileTools/Simple-SMS-Messenger

app/src/main/res/values-es/strings.xml
I changed in some parts "managing" to "send" because it sounds better
=> Create strings.xml Español

app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt
Here is, only inverting the buttons
=> Inverting notification shortcuts

app/src/main/res/values-zh-rCN/strings.xml
=> Add zh-CN translation.

app/src/main/res/values-da/strings.xml
I have translated strings.xml. I'm new to GitHub, so i dont know how it all works. I hope you can use my translation.
=> Danish Translations added

app/src/main/res/values-pl/strings.xml
Hi. I've added a Polish translation.
=> Added Polish translation

app/src/main/res/values-pl/strings.xml
Hi. I've noticed that in the other apps an app name is translated to Polish, so I also did it here.
=> Translated app name to Polish

app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/SettingsActivity.kt, app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt, app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt, app/src/main/kotlin/com/simplemobiletools/smsmessenger/helpers/Config.kt, app/src/main/kotlin/com/simplemobiletools/smsmessenger/helpers/Constants.kt, app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/DirectReplyReceiver.kt, app/src/main/res/layout/activity_settings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-id/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-ml/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sk/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
Hi,
I've added an option to remove diacritics. It's available to turn on in settings. It works both in standard sending and from notification.
https://user-images.githubusercontent.com/85929121/132183746-16969760-dfbd-4f93-b831-ca185db87445.mp4
=> Added removing diacritics (#29)

app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ThreadAdapter.kt
**Notes**
- handle long-press of attachment
https://user-images.githubusercontent.com/25648077/141703191-b2c45c27-6197-4ca2-b403-3c32482d07cd.mov
=> handle long-press of attachment

app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt
Hi,
I've added the functionality to show multiple SMS messages in a notification:
- I'm using here an Android's ready `MessageStyle` to display new messages that supports multiple messages. Unfortunately, it means that notification looks are a bit changed (will look more like other messaging apps), and they differ between system versions and devices.
- It works only if a user haven't removed notification. It adds new message bodies to old notification (or to be technically correct - it creates new notification based on an old one).
- It doesn't work on Android older than 7.0 and `Sender only` visibility. In these two cases, I've left the old way of displaying messages.
- On Androids older than 6.0 I couldn't access old notification. On Android 6.0 there is a bug that `MessageStyle` …
=> Added multiple messages in notification

app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/SmsReceiver.kt
Hi,
I've noticed that in received SMS notification there was a missing contact photo, there was always a placeholder instead. I've added a support for it.
I've tested it both on emulator and real device, and it works without any problem.
**Before:**
https://user-images.githubusercontent.com/85929121/149190737-3378027a-eed3-4d94-9c8e-944adaa7c17d.mp4
**After:**
https://user-images.githubusercontent.com/85929121/149190764-68163cca-6e82-44e4-927a-8f03944584c8.mp4
=> Added contact photo to notification

app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt, app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ThreadAdapter.kt, app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt
Closes #104
https://user-images.githubusercontent.com/85929121/150682542-8f0e22a6-0952-4f0a-9b82-e0c867cc2e8e.mp4
=> Added opening contact details from the conversation view (#104)

app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
Quick implementation of FR #321. 
Android Studio is not happy about concatenating, but since it's strictly numbers, I guess it should display the same way in all language ? 
EDIT: small video showing it working :)
https://user-images.githubusercontent.com/45575529/157858707-7accbcfc-001d-4009-b6a6-adabb96155a0.mp4
=> Added message counter

app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt, app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ThreadAdapter.kt, app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt, app/src/main/kotlin/com/simplemobiletools/smsmessenger/helpers/Constants.kt
=> Allow displaying older messages

app/build.gradle, app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt, app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/DirectReplyReceiver.kt, app/src/main/res/xml/provider_paths.xml
**Preview:**
**Note:** Target SDK was set to 33 (Android 13)
=> Allow attaching captured photos from camera

app/build.gradle, app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/MmsReceiver.kt
Once https://github.com/tibbi/android-smsmms/pull/8 is merged, `build.gradle` must be updated with the latest android-smsmms
=> Add the ability to block numbers by pattern

app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/SearchResultsAdapter.kt, app/src/main/res/layout/activity_search.xml
- Speed up search by [removing the nested scroll view](https://stackoverflow.com/a/64679001/8475376)
- Darken date text color (was too light in light themes)
=> Search improvements

app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ConversationsAdapter.kt
Fixes #455
**Before:**
**After:**
=> Fixed pin indicator color (#455)

app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt, app/src/main/kotlin/com/simplemobiletools/smsmessenger/extensions/Context.kt
https://github.com/tibbi/android-smsmms/pull/10 has to be merged for things to work
=> Persist subscription id when sending sms messages

app/src/main/kotlin/com/simplemobiletools/smsmessenger/receivers/SmsReceiver.kt
This removes the unnecessary update/change animation in the UI when new messages are refreshed.
=> Save sender name, photo when receiving a message

app/src/main/kotlin/com/simplemobiletools/smsmessenger/activities/ThreadActivity.kt
Fixes #573
**Before:**
https://user-images.githubusercontent.com/85929121/213862414-b08a4144-ccb9-47fa-92e3-138246b2c13b.mp4
**After:**
https://user-images.githubusercontent.com/85929121/213862430-8e347de6-4c0e-4ac7-9602-7c56e29ad94a.mp4
=> Fixed notification not disappearing on resume (#573)

app/src/main/kotlin/com/simplemobiletools/smsmessenger/messaging/Messaging.kt, app/src/main/kotlin/com/simplemobiletools/smsmessenger/messaging/MessagingUtils.kt
Closes https://github.com/SimpleMobileTools/Simple-SMS-Messenger/issues/614
=> Fix MMS issues

app/src/main/kotlin/com/simplemobiletools/smsmessenger/helpers/MessagesImporter.kt
This allow larger backups to be imported by avoiding memory allocation errors when trying to parse the entire JSON file at once.
=> Stream json during import fixes #329

app/src/main/kotlin/com/simplemobiletools/smsmessenger/adapters/ConversationsAdapter.kt
=> Fixed deleting notification after deleting conversation ( #637)

gradle/libs.versions.toml
This includes changes from https://github.com/tibbi/android-smsmms/#16
=> Update android-smsmms library
